In [15]:
1-2

-1

In [2]:
4*5

20

In [3]:
7/5

1.4

In [4]:
3**2

9

In [5]:
type(10)

int

In [6]:
type(1.7)

float

In [7]:
type('hello')

str

In [8]:
x=10
print(x)

y=3.14
x*y

10


31.400000000000002

In [12]:
a=[1,2,3,4,5]
print(a)
len(a)
a[0]

[1, 2, 3, 4, 5]


1

In [13]:
a[4]=90
print(a)

[1, 2, 3, 4, 90]


In [16]:
a[0:2]

[1, 2]

In [17]:
a[:3]

[1, 2, 3]

In [18]:
a[:-1]

[1, 2, 3, 4]

In [19]:
me = {'height':180}
me['height']

180

In [20]:
me['height']=70
print(me)

{'height': 70}


In [23]:
sum = 0
for i in range(0,10,1):
  sum = sum + i
  print(i,sum)

0 0
1 1
2 3
3 6
4 10
5 15
6 21
7 28
8 36
9 45


In [26]:
def maximum(x,y):
  if x>y:
    return x
  elif x==y:
    return 'The numbers are equal'
  else:
    return y
print(maximum(2,3))

3


In [28]:
class Person:
  def __init__(self,name):
    self.name = name
  def say_hi(self):
    print('Hello, my name is', self.name)

p=Person('파이썬')
p.say_hi()

Hello, my name is 파이썬


In [29]:
major_g = {'1학년':5,'2학년':9,'3학년':12,'4학년':12}
print(major_g)
print(major_g['2학년'])

major_g['2학년'] = 11
print(major_g['2학년'])

{'1학년': 5, '2학년': 9, '3학년': 12, '4학년': 12}
9
11


In [36]:
import numpy as np
x = np.array([1.0,2.0,3.0])
print (x)
type (x)

[1. 2. 3.]


numpy.ndarray

In [37]:
y = np.array([2.0,4.0,6.0])
x+y

array([3., 6., 9.])

In [38]:
x-y

array([-1., -2., -3.])

In [39]:
x*y

array([ 2.,  8., 18.])

In [40]:
x/y

array([0.5, 0.5, 0.5])

In [41]:
x/2

array([0.5, 1. , 1.5])

In [42]:
A = np.array([[1,2],[3,4]])
print (A)

[[1 2]
 [3 4]]


In [43]:
A.shape

(2, 2)

In [44]:
A.dtype

dtype('int64')

In [45]:
B = np.array([[3,0],[0,6]])
A+B

array([[ 4,  2],
       [ 3, 10]])

In [46]:
A*B

array([[ 3,  0],
       [ 0, 24]])

In [48]:
A*10

array([[10, 20],
       [30, 40]])

In [49]:
A = np.array([[1,2],[3,4]])
B = np.array([10,20])
A*B

array([[10, 40],
       [30, 80]])

In [50]:
X = np.array([[51,55],[14,19],[9,4]])
print (X)

[[51 55]
 [14 19]
 [ 9  4]]


In [51]:
X[0]

array([51, 55])

In [52]:
X[0][1]

55

In [53]:
for row in X:
    print (row)

[51 55]
[14 19]
[9 4]


In [54]:
X = X.flatten()
print (X)

[51 55 14 19  9  4]


In [55]:
X[np.array([0,2,4])]

array([51, 14,  9])

In [56]:
X > 15

array([ True,  True, False,  True, False, False])

In [57]:
X[X>15]

array([51, 55, 19])